mysql:
  host: 127.0.0.1
  username: root
  password: 12345678
  db: sausage_shooter
  port: 3306
gm:
  token: uApHngkjnJCsZLXwvx1j
  pid: 110
  branch: master
  url: https://git.xindong.com/api/v4
user:
  token: uApHngkjnJCsZLXwvx1j
  pid: 107
  branch: master
  url: https://git.xindong.com/api/v4