mysql:
  host: 172.26.32.12
  username: sausage
  password: sausage_shooter
  db: sausage_shooter
  port: 3306
gm:
  token: uApHngkjnJCsZLXwvx1j
  pid: 110
  branch: dev
  url: https://git.xindong.com/api/v4
user:
  token: uApHngkjnJCsZLXwvx1j
  pid: 107
  branch: master
  url: https://git.xindong.com/api/v4
jwt:
  signkey: sdkjflkdgjlkdfg